language: rust
rust: nightly
cache:
  - cargo
  - $TRAVIS_BUILD_DIR/testing/target

before_script:
  - rustup target add i686-unknown-linux-gnu
  - rustup target add thumbv7em-none-eabihf
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/cargo-xbuild || cargo install cargo-xbuild)
  - (test -x $HOME/.cargo/bin/bootimage || cargo install bootimage)
  - cargo install-update -a

script:
  - cargo build
  - cargo test
  - cargo build --features deny-warnings
  - bootimage test --manifest-path testing/Cargo.toml
  - cargo build --target i686-unknown-linux-gnu
  - cargo build --target thumbv7em-none-eabihf

addons:
  apt:
    packages:
    - qemu-system-x86
