# Documentation: https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      pool_name: 'Linux'
      image_ame: 'ubuntu-16.04'
    mac:
      pool_name: 'macOS'
      image_name: 'macos-10.13'
    windows:
      pool_name: 'Windows'
      image_name: 'vs2017-win2016'

pool:
  name: $(pool_name)
  vmImage: $(image_name)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo This is pipeline $(System.DefinitionId)
    echo OS: $(variables['Agent.OS'])
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
